### ISSUE TITLE
For each of an author’s aliases, modify initial query based on lexical rules

### ISSUE THREAD

**Issue by michaelbales1** [wcmc-its/ReCiter#100]
### Background and approach

We have identified five special circumstances that may pose challenges when using authors’ names to identify publications. These are 1) the author has a nickname; 2) the author’s last name has changed, most often due to marriage; 3) the author’s name has a suffix; 4) the author’s last name contains a space or hyphen; and 5) the author uses their middle name as though it were their first name.

When institutional records indicate that the author has a nickname (<b>circumstance 1</b>), or the last name has changed due to marriage (<b>circumstance 2</b>), these must be supplied to ReCiter as alternate name representations (aliases).

The aliases are to be retrieved by querying for rows that match the target author’s cwid in the rc_identity_directory table.

Author names affected by circumstances 3, 4, and 5 have one or more lexical signals that can be recognized by ReCiter. Once one of these three circumstances is recognized for any of an author’s aliases, ReCiter must then use a set of rules that correspond to the circumstance to generate name variants from the alias. Each of these name variants for all of the author’s aliases is combined using an OR query to maximize the recall of the PubMed query.

For the purposes of this project, code to support circumstances 1 and 2 is not required; for authors affected by either of these circumstances, multiple name representations will be supplied to ReCiter from institutional data as aliases. All aliases are then passed through the code below to deal with circumstances 3, 4, and 5 should they exist.
### Circumstance 3. The author’s name has a suffix.

When an author’s name includes a suffix of JR, II, III, or IV, generate a lexical variant with the alias and another without the alias. For example, if the author’s name is Paul Jones II, these two variants should be added to the query:
- Jones Mark[au] OR
- Jones Mark II[au]
### Circumstance 4. The author’s last name contains a space or hyphen

If the last name contains a space, modify the PubMed query so that a name’s possible variants are included. Add the following variations to the query:
- FirstTermFromLastName, FirstInitial[au] OR
- FirstTokenFromLastName-LastTokenFromLastName, FirstInitial[au]
- FirstTokenFromLastName LastTokenFromLastName, FirstInitial[au]

If the last name contains a hyphen, add the following variations to the query:
- FirstTokenFromLastName, FirstInitial[au] OR
- FirstTokenFromLastName-LastTokenFromLastName, FirstInitial[au]

Examples
- CWID ses9022, first name: Selin; last name: Somersan Karakaya. The PubMed query would be: "Somersan Karakaya S[au] OR Somersan-Karakaya S[au] OR Somersan S[au]"
- CWID csjohnso, first name: Carol; last name: Storey-Johnson. The PubMed query would be "Storey-Johnson C[au]" OR Storey C[au]"
### Circumstance 5. The author’s first name consists of a single letter

If the first name consists of a single letter, add the following variations to the query:
- LastName FirstInitial[au] OR
- LastName MiddleInitial[au] OR
- LastName MiddleInitialFirstInitial[au] OR
- LastName FirstInitialMiddleInitial[au]

Examples:
- W. Clay Bracken
- M. Flint Beal

After the rules for circumstances 3, 4, and 5 have been applied when appropriate for each of a target author’s aliases, all variations are combined into a single query. A name in which several of these conditions occur may generate a number of possible permutations. This is okay.
### Circumstance 6. The author’s first name contains a space or hyphen

When the author's first name contains a space, this may indicate that the author uses his or her middle name as a first name.

This query can be used to identify such cases, along with cases in which the first name field only includes a first initial:

select \* from rc_identity
where (char_length(first_name) < 2 OR
     (char_length(first_name) = 2 and first_name like '%.') OR
     (mid(first_name,2,1) = ' ')
     )

An example is J David Warren, for whom "J David" appears in the first name field, while the middle name field is null.

Add the following variations to the query:
- LastName, FirstLetterOfFirstTokenFromFirstName[au] OR
- LastName, FirstLetterOfSecondTokenFromFirstName[au]

In the case of J David Warren, the updated query would be:

Warren J[AU] OR Warren D[AU]

**Comment by paulalbert1** [comment]
This should be addressed by our recent changes. If it hasn't, we can revisit this issue.
