### ISSUE TITLE
Explore how scores improve as asserted publications are used to select clusters rather than seed them

### ISSUE THREAD

**Issue by michaelbales1** [wcmc-its/ReCiter#13]
As ReCiter is a greedy algorithm that does agglomerative clustering, we may assume that performance will improve if we provide one or more "seed" articles that are known to have written by an author. We wish to quantify the extent to which precision and recall improve in specific cases. This project involves running ReCiter several times for a set group of authors, in each case varying the number of "seed" articles provided. The results of this study could be written up and submitted to a journal.

**Comment by paulalbert1** [comment]
Not being actively worked on. Can re-open if necessary.
