### ISSUE TITLE
Articles are assigned to target author based on affiliation match even though first names are in conflict

### ISSUE THREAD

**Issue by michaelbales1** [wcmc-its/ReCiter#133]
Example is CWID wex2004 (note that this person is not among the 63 names in the gold standard, so to reproduce this error it is necessary to add a row to rc_identity based on data in the online directory). For seven of the false positives the first name is "Weifeng" which is in conflict with the first name that actually corresponds to this CWID. In cases where first name in publication metadata are in conflict with first name in rc_identity, articles should not be assigned to the target author.
### Examples
- wex2004 (Weizhen Xu) - 19648924, 19561614, 17570691, 17259987, 16960154, 16301649 (all have the name Weifeng Xu)
- mil2041 (Minwei Liu) - 23965901 (Minetta C. Liu)
- xul2005 (Xue Li) - 26628621 (Ying Liu)

All of these names are very common, so I would suggest troubleshooting this issue by putting into place a temporary hack such that it ONLY retrieves records with these PMIDs.

**Comment by paulalbert1** [comment]
This should be addressed by the hopefully more reliable changes made to how we identify targetAuthor.
