### ISSUE TITLE
Use data from known and rejected prior publications to improve accuracy

### ISSUE THREAD

**Issue by michaelbales1** [wcmc-its/ReCiter#135]
Known publication data for authors is stored in rc_gold_standard_pmids (to be renamed rc_output). For the purposes of this description a "known" publication is defined as a publication that is known to have been authored by the given author. A "rejected" publication is a publication that is known not to have been authored by the given author. The goal of this enhancement is to use known publication data as follows:
- To populate the first cluster in phase one clustering, and
- To populate the appropriate tables in the ReCiter database such that publication metadata from these publications are used to improve system accuracy, in terms of precision and recall.

The steps required are:
1. Look for known and rejected publications in rc_gold_standard_pmids (to be renamed rc_output)
2. Retrieve articles for known PMIDs that don't exist in data directory on ReCiter server
3. Ingest the publication metadata into the appropriate tables in the ReCiter database, as specified in Table 1 below (although if the first name in an accepted publication consists only of a first initial, do not add it to rc_identity_alias)
4. Based on existing logic e-mails and aliases are included in the initial query, joined by "OR" statements
5. In Phase 1 clustering, use the list of known publications to form the first cluster
6. Based on existing logic the data ingested in Step 3 above are used to improve accuracy in the remaining downstream phases of the ReCiter algorithm
7. In Phase 2 cluster selection, exclude clusters that contain one or more rejected publications
8. In Phase 3 reassignment, with the exception of rejected publications, allow articles in excluded clusters to be reassigned to the target author (note that this constitutes a minor modification to the article reassignment code that already exists)
9. Author a cron script to invoke the preceding on a regular basis

Table 1. Publication metadata and corresponding ReCiter database table

| Data type | Table to which to append datum |
| --- | --- |
| First, middle, last name | rc_identity_alias |
| Affiliation keywords | rc_identity_institutions |
| E-mail address | rc_identity_email |
| MeSH major terms | rc_identity_keyword |
| Co-authors | rc_identity_relationship |

**Comment by paulalbert1** [comment]
This should also include an API-based mechanism for writing feedback back to ReCiter.

**Comment by paulalbert1** [comment]
It looks like this will be addressed by #231.
