### ISSUE TITLE
Create separate project for publications web service

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter#164]
Here are the functionalities this web service needs to provide:

- Everything ReCiter already does.
- Handle requests for the following.
  - Given either a ScopusDocID, DOI, or PMID, provide:
    - Citation count and timestamp (from Scopus)
    - Publication type ("subtype") (from PubMed and Scopus)
    - Affiliation of author (from Scopus)
    - Whether the record still exists. In cases, where a ScopusDocID returns null (this happens sometimes), the service should indicate no result returned.
  - Given a DOI or PMID, provide the corresponding ScopusDocID.
  - Given a PMID, return the full XML.
http://localhost:8080/pubmed/query/25091197
  - Given a PMID, provide updated MeSH and MeSH major from PubMed. http://localhost:8080/pubmed/query/bales%20m[au]?fields=medlineCitation.meshHeadingList
  - Given a PMID, provide updated funding statement.
http://localhost:8080/pubmed/query/bales%20m[au]?fields=medlineCitation.article.grantList
  - Given a PMID, provide updated PMCID. http://localhost:5000/api/v1/article/otherid/26174865
  - Given a PMID, provide updated status. 
http://localhost:5000/api/v1/article/medlinecitationstatus/26174865
  - Given a PMID, provide updated publication types.
http://localhost:5000/api/v1/article/publicationtypelist/26174865
  - Given a search string of any kind, do a generic search against PubMed. For example: "electronic health records" or "10.100.1452[doi]" or "kaushal r[au]"
http://localhost:5000/api/v1/articles/kaushal%20r[au]

  - Pagination for every 200 results.

Lookups against Scopus should include instoken and API key.

### PubMed and Scopus, all data
```
search=[PubMed-specific search]?PubMedThenScopus=Yes
```
- all data in PubMed and Scopus

### PubMed only, all data
```
search=[PubMed-specific search]?PubMedOnly=Yes
```
- only data from PubMed

###  PubMed or Scopus, certain data
```
search=[Scopus-specific search]?ScopusOnly=Yes&fields=citation-count,affiliation-name
search=[PubMed-specific search]?PubMedOnly=Yes&fields=pmcid
```
- returns any Scopus specific data like citation count, publication type, affiliation ID, affiliation name

**Comment by jl987-Jie** [comment]
add v1
