### ISSUE TITLE
Allow ReCiter to use clients to retrieve PubMed and Scopus articles 

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter#168]
Clients should be able to:

1. Look up publications by user identity. This triggers connections to the PubMed and Scopus APIs.

2. Look up publications directly in one or both bibliographic sources without using the disambiguation service. It should meet WCM's existing needs for a canned search. Or, to describe it a different way, the lookup should be no less versatile than connecting directly with these systems' respective APIs. Also, it shouldn't require pre-specifying the type of search.

Sample searches for PubMed:
```
Kaushal Rainu
Kaushal R[au]
metagenomics
23576059 24882717
10.1007/s12026-013-8413-z  10.1038/cmi.2010.77
```

Sample searches for Scopus:
```
Kaushal Rainu
metagenomics
23576059
(AU-ID(12143909200) OR AU-ID(55334671500)
SCOPUS-ID(9644266684)
doi(10.1007/s12026-013-8413-z)
( AF-ID ( "Weill Cornell Medical College"   60007997 )  OR  AF-ID ( "Weill Cornell Medical Center"   60019868 )  OR  AF-ID ( "Weill Graduate School of Medical Sciences"   60000247 )  OR  AF-ID ( "Weill Cornell Medicine-Qatar"   60072750 )  OR  AF-ID ( "Cornell College"   60003453 )  OR  AF-ID ( "Rogosin Institute"   60010570 )  OR  AF-ID ( "Weill Cornell Medicine Feil Family Brain & Mind Research Institute"   60109878 )  OR  ( ... )  OR  AF-ID ( "Cornell Internal Medicine Associates"   60012732 ) ) 

```

3. In either scenario, client should be able to choose whether to allow matching between PubMed and Scopus.

**Comment by sarbajitdutta** [comment]
Done
