### ISSUE TITLE
Full citation isn't being returned for articles retrieved via email strategy

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter#173]
For example: https://www.ncbi.nlm.nih.gov/pubmed/?term=paa2013%40med.cornell.edu for paa2013.

The reason why it's necessary to have the full citation is for displaying all the proper evidence.

**Comment by sarbajitdutta** [comment]
This is addressed in https://github.com/wcmc-its/ReCiter-Scopus-Retrieval-Tool/pull/1

**Comment by paulalbert1** [comment]
Fixed in #184.
