### ISSUE TITLE
feature-generator/by/uid API should allow user to specify certain parameters

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter#179]
1. By default, API should return all fields. However, requestor can specify particular fields, e.g., `?fields=doi,pmid`
2. Some users want to trigger a refresh (which would be more current but take more time) while others want data right away. To trigger a refresh, request can use the parameter, `refresh=true` while the second group can use this parameter `?refresh=false`.
3. Pagination (should cover Maurice's use case)
4. Sort by date ascending, date descending, evidence score descending, evidence score ascending.
5. User assertion = true, false. True means only include publications that have a positive assertion in the gold standard. False means only include publications have no assertion; this gets all pending publications.
6. Search by CWID, DOI, PMID
7. `Retrieval=all` or `Retrieval=update` The former re-retrieves all articles. The latter only retrieves articles published since last run (and is the default).

**Comment by sarbajitdutta** [comment]
This has been realized.

Question is do we still want to filter by certain fields for feature-generator? or do we allow that feature to be part of article generator?
@paulalbert1

**Comment by paulalbert1** [comment]
Let's close this issue until such time as we get a real-world use case for additional features.

**Comment by sarbajitdutta** [comment]
Lets try to implement this

**Comment by paulalbert1** [comment]
Looks done to me.
