### ISSUE TITLE
Improve method for identifying target author

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter#185]
Every paper - including those from the gold standard and those where the ReCiter algorithm opts not to make a match - should have one and only one target author.

All matching should be done in a case-insensitive way.

The output of this judgment should be:
- done at an early state in the algorithm
- stored in the Analysis table (which hasn't been created yet)
- used for analysis
- used as a field to be output into the feature generator API. 

Some of this work is being done by getCorrectAuthor.

## Order of operations
- Retrieve records from PubMed and according to the range of retrieval strategies
- Get complimentary data from Scopus
- Identify targetAuthor

## Logic

**Attempt email match**
- if 0 results, go to next.
- if 1 result, stop.
- if > 1 result (e.g., 28265069 for OS Andersen), assign remaining authors as false, go to next.

**Attempt strict last name, strict middle name, and strict first name match.**
- if 0 results, go to next.
- if 1 result, stop.
- if > 1 result, assign remaining authors as false, go to next.

**Attempt strict last name, middle initial, and strict first name match.**
- if 0 results, go to next.
- if 1 result, stop.
- if > 1 result, assign remaining authors as false, go to next.

**Attempt strict last name and strict first name match.**
- if 0 results, go to next.
- if 1 result, stop.
- if > 1 result, assign remaining authors as false, go to next.

**Attempt strict last name and partial first name match, in which article is substring of identity.**
- if 0 results, go to next.
- if 1 result, stop.
- if > 1 result, assign remaining authors as false, go to next.

**Attempt strict last name and partial first name match, in which identity is substring of article.**
- if 0 results, go to next.
- if 1 result, stop.
- if > 1 result, assign remaining authors as false, go to next.

**Attempt strict last name and first initial match.**
- if 0 results, go to next.
- if 1 result, stop.
- if > 1 result, assign remaining authors as false, go to next.

**Attempt strict last name and middle initial to first initial, and first initial to middle initial match.**
- if 0 results, go to next.
- if 1 result, stop.
- if > 1 result, assign remaining authors as false, go to next.

**Attempt partial last name and first initial match.**
- if 0 results, go to next.
- if 1 result, stop.
- if > 1 result, assign remaining authors as false, go to next.

**Attempt strict last name match.**
- if 0 results, go to next.
- if 1 result, stop.
- if > 1 result, assign remaining authors as false, go to next.

**Attempt strict first name match.**
- if 0 results, go to next.
- if 1 result, stop.
- if > 1 result, assign remaining authors as false, go to next.

**Attempt full last name match from article to partial last name from identity. (e.g., Somersan-Karakaya)**
- if 0 results, go to next.
- if 1 result, stop.
- if > 1 result, assign remaining authors as false, go to next.

**If one of the names in Article is for a “Collective Author” ([examples](https://www.ncbi.nlm.nih.gov/pubmed/?term=7490148+22825588+25112663) - this is for rbdevere), map to that.**
- if 0 results, assign all authors as false.
- if 1 result, stop. Assign that author as true.
- if > 1 result, assign ALL authors as false, go to next.

Assign all authors as false.

**Comment by sarbajitdutta** [comment]
The last step to check for collective author is ON HOLD since we need to bring in additional data from pubmed namely Contributor list

**Comment by paulalbert1** [comment]
@sarbajitdutta - For `ses9022`, I got this:
```
19:37:49.914 [http-nio-5000-exec-4] INFO  r.a.e.t.TargetAuthorSelection - There was no target author found for 29117776
19:37:49.947 [http-nio-5000-exec-4] INFO  r.a.e.t.TargetAuthorSelection - There was no target author found for 27398323
19:37:49.950 [http-nio-5000-exec-4] INFO  r.a.e.t.TargetAuthorSelection - There was no target author found for 28352671
19:37:49.967 [http-nio-5000-exec-4] INFO  r.a.e.t.TargetAuthorSelection - There was no target author found for 28287838
```

Is the above logic wrong??

**Comment by paulalbert1** [comment]
I've noticed that email match is not very effective. We might consider commenting it out - or moving down to position 6 in the rubric.

![Screen Shot 2019-04-01 at 7 39 57 AM](https://user-images.githubusercontent.com/3651640/55325857-3bdf8080-5454-11e9-9269-6574d0a4492a.png)

**Comment by paulalbert1** [comment]
No target author for aae2001
<img width="1089" alt="aae2001" src="https://user-images.githubusercontent.com/3651640/56093519-d0f06980-5e97-11e9-9cdd-7c2703a39024.png">

**Comment by sarbajitdutta** [comment]
Add deAccent to the AuthorSanitizationUtil.

**Comment by paulalbert1** [comment]
Here's a tricky case
amr2011 - https://www.ncbi.nlm.nih.gov/pubmed/27922594

Should match to
```
<LastName>Rajadhyaksha</LastName>
<ForeName>Anjali M</ForeName>
```

**Comment by paulalbert1** [comment]
Fixed.
