### ISSUE TITLE
In populating goldStandard table, retrieve CWID-PMID relationship from T32_citation

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter#193]
An example of a record that should be retrieved:
```
ccole,25954570
```

Dedupe with records retrieved from wcmc_document

**Comment by sarbajitdutta** [comment]
Is this still required @paulalbert1 ?

**Comment by paulalbert1** [comment]
No - it's not. We can do this authoritatively in ReCiter once we populate identities from alumni.
