### ISSUE TITLE
Use name aliases harvested from accepted publications to improve recall

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter#199]
Find author names where `targetAuthor = true` that are in the goldstandard table not returned by lastName firstInitial lookup.

If the name is used frequently and consistently enough (logic to be determined), add name to known aliases and use to look up additional publications.

For now, this is effort purely an analysis effort.

**Comment by sarbajitdutta** [comment]
Is this required @paulalbert1 ?

**Comment by paulalbert1** [comment]
Not now, no. But it's actually a decent idea for future development.

That said, this may be a less useful approach than the UI we describe in the ASMS project, in which top names, relationships, etc. are displayed in a profile section.

Let's put this on hold for now.

**Comment by paulalbert1** [comment]
May be addressed by #320
