### ISSUE TITLE
Improvements needed for handling gold standard (summary)

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter#204]
Here are the existing issues with gold standard:
1.  uid = `paa2013` has a PMID of `23370376` in the gold standard, but it's not marked as `userAssertion=true` in the feature generator output.
2. We need to keep track of true / false / null assertions. See #194
3. Gold standard can be used in different modes: testing and evidence. This should be able to be passed in as a parameter at the feature generator stage. See #169
4. Rejected articles should be included in the feature generator output. User assertion should be false.
5. Consider renaming goldStandard to userAssertion.

**Comment by sarbajitdutta** [comment]
The 1st and 2nd and 4th issue has been addressed in https://github.com/wcmc-its/ReCiter/tree/target_author_selection%23185 branch
