### ISSUE TITLE
Feature generator should include all parameters used in API output

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter#222]
This will allow us to easily compare different test runs against each other.

**Comment by sarbajitdutta** [comment]
Please explain @paulalbert1

**Comment by paulalbert1** [comment]
The idea was to include all of these fields, some of which we already capture.

We could also include in the output: totalStandardizedArticleScore, filterByFeedback, analysisRefreshFlag, and retrievalRefreshFlag. This would somewhat improve the ability for people to understand the significance of these files.

This is not a high priority.

<img width="746" alt="screen shot 2019-02-19 at 4 38 09 pm" src="https://user-images.githubusercontent.com/3651640/53049378-eed7ba00-3464-11e9-8247-a33d4fe79b58.png">

**Comment by paulalbert1** [comment]
Closing for now. We can re-open as the need arises.
