### ISSUE TITLE
Integrate ReCiter API with ASMS web user interface

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter#238]
ASMS should: retrieve suggestions from ReCiter API including suggested, rejected, and accepted articles, along with all the evidence; record and log feedback. There are a number of steps here that could be broken out into individual issues but for now, I'm keeping them as one issue.

Key deliverables:
- ASMS has account that has GET/POST access for all the function within the ReCiter API controller.
- Use these API parameters:
    - use.scopus.articles=true
    - use.gold.standard.evidence=true
    - totalArticleScoreStandardized = 6
    - refreshFlag = TRUE
- Return all pubs where globalScore >= totalArticleScoreStandardized, AND publication is accepted or rejected
- Upon navigating to a faculty's ASMS profile, retrieve records from feature-generator API. If the computation does not exist or the records have not been retrieved, perform the missing steps. Modal window at top notifies user that retrieval and/or recomputation is in progress. Ideally, the interface would refresh with updated results once these events are completed.
- Display evidence in human-readable format. (Paul to provide PHP.)
  - On mouseover of global score, display raw score 
- For each article, user can click on "Accept", "Reject", or "Pending." This does several things:
  - In the interface, it instantly moves article between queues.
  - Logs action in goldStandard table along with the user who made it, and when it was made.
- User can look up and add additional PMIDs 
- Create identity records in ASMS for users who are being imported into ReCiter. This includes past and present PhD students and MD-PhD students

### Individual record

![image](https://user-images.githubusercontent.com/3651640/47655156-c4cf5480-db62-11e8-8b24-2f085c002852.png)

### Show evidence

![asms publications interface-revised 001](https://user-images.githubusercontent.com/3651640/47655070-96ea1000-db62-11e8-901a-e84edeaf5200.png)

### Feedback

If a user clicks Accept, Reject, or Undo in any of the tabs, update GoldStandard table via API accordingly each time an update occurs.

Also, display a thin banner (see below) which counts the number of changes that have made since the last time the feature generator ran. 

User can click on "Click to refresh" which triggers the feature generator to rerun where retrievalRefreshFlag = "only newly added publications."

When feature generator is working a "busy spinner" should appear indicating that new records are being returned with the message, "Recomputing"

This banner should be displayed on ALL tabs and remain until user clicks the X to close the banner or clicks to refresh.

<img width="1010" alt="screen shot 2018-10-29 at 6 19 49 pm" src="https://user-images.githubusercontent.com/3651640/47683875-552f8880-dba7-11e8-84d4-d97a20b57589.png">

### Update profile

User can click on "Update Profile" tab to see identity data that can be used to improve suggestions. (This is complicated. More detailed requirements to follow.)

![asms publications interface-revised1 001](https://user-images.githubusercontent.com/3651640/47723860-c749b100-dc2b-11e8-83e3-af26d1b124c5.png)

### Settings
![asms publications interface-revised 004](https://user-images.githubusercontent.com/3651640/44591067-b9d6fd00-a78a-11e8-88c3-f381e6498046.png)

**Comment by sarbajitdutta** [comment]
Relationship badges
- HR
- Mentor
- Mentee
- Co-investigator
- Senior Author

Institutional match badges
- Home Institution
- Institutional Collaborator
- Individual Affiliation

**Comment by paulalbert1** [comment]
Mostly fixed. Mockup has changed enough that we will handle this elsewhere.
