### ISSUE TITLE
Import keyword and affiliation data from POPS API

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter#239]
### Option 1 (preferred)

1. Look for presence of this field in Enterprise Directory.

```
labeledURI;pops: http://weillcornell.org/clcole
```

Examples: ccole, zrosenw, brf9046

2. If user has that field, it means they have data in the POPS system.

3. Load this URL:
http://pops.weillcornell.org/providerbyshortname/[cwid].json

### Option 2

Load this URL for any faculty:
http://pops.weillcornell.org/providerbyshortname/[cwid].json

Some users will have it, some won't.

### Keywords

1. Look for these fields
```
primary_specialties > name
board_certified_specialties > name
medical_surgical_specialties > name
problem_procedure > name
```

2. Load these data into identity.keywords

3. Add type "clinical"

### Institutions

1. Look for these fields
```
training > institution
```
2. Load unique data into identity.institutions, assigning type "clinical"

### Departments

1. Looks for these fields
```
department > department_name
division > division_name
practices > practice_name
```

2. Load these data into identity.departments, assigning type "clinical"

**Comment by sarbajitdutta** [comment]
I think this was addressed in InstClient. Please confirm @paulalbert1

**Comment by sarbajitdutta** [comment]
If you want to revisit this lets open it later.

**Comment by paulalbert1** [comment]
Affiliation was imported, keyword was not. That's okay for now. Let see if this is even needed. Keeping this closed for now.
