### ISSUE TITLE
Create keywordScoringStrategy

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter#240]
Prerequisite: #239

Known keywords for a given author are useful for matching, but only if they occur relatively rarely. 

1. Retrieve keywords from identity.keywords for author under consideration.

2. Retrieve mesh major terms from candidate article.

3. Preprocess both. Remove spaces, dashes, and commas.

4. Get constants from application.properties.
```
keywordScoreThreshold: 150000
keywordScoreMaxWeight: 5
```

5. Retrieve count from MeshTerm table. Let's call that meshTermCount.

6. Attempt to match identity.keywords to mesh major terms for as many keywords as possible. We will only consider terms where meshTermCount < keywordScoreThreshold.

7. If there's a match, calculate the following:
```
(keywordScoreThreshold - meshTermCount) / keywordScoreMaxWeight
```
Output the following:, for example
```
identity.keyword = Pediatric endocrinology
article.keyword = Pediatric endocrinology
keywordScore = 3.2
```
Else, do nothing.

**Comment by sarbajitdutta** [comment]
Is this still required @paulalbert1

**Comment by paulalbert1** [comment]
Nope
