### ISSUE TITLE
Update articleCountScoringStrategy so it better accounts for retrieval counts in strict mode

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter#278]
With issue #228, we count the number of records returned. This strategy ignores the possibility that the returned records came during strict retrieval mode. For example, `yiwang` might have 800 articles. 

We should change the count used for this score so that it's 2,000 or whatever the current `searchStrategy-leninent-threshold` is.

The language of the original issue has been updated to reflect this.

**Comment by sarbajitdutta** [comment]
I think this was addressed. Can you check? @paulalbert1

**Comment by paulalbert1** [comment]
It was not. The point score highlighted below would be a negative number if it were.

<img width="1034" alt="screen shot 2019-02-19 at 4 34 40 pm" src="https://user-images.githubusercontent.com/3651640/53049151-6eb15480-3464-11e9-9302-3070cb2fefcf.png">

**Comment by sarbajitdutta** [comment]
This was completed. Added a new field in ESearchResult table.
