### ISSUE TITLE
Implement roles 

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter#279]
Here are the roles and APIs should they should be able to access.

  | Admin role | Data display and feedback role | Department role
-- | -- | -- | --
Example users | Institutional client | ASMS | MD-PhD program; Physiology & Biophysics
Needs API key | Yes | Yes | Yes
Location | Must be inside network | Must be inside network | Can be outside network
/reciter/find/identity/by/uid/ | Yes | No | No
/reciter/find/identity/by/uids/ | Yes | No | No
/reciter/identity/ | Yes | No | No
/reciter/feature-generator/by/uid | Yes | Yes | Yes - but don't include evidence
/reciter/goldstandard/ (POST) | Yes | Yes | No
/reciter/goldstandard/   (PUT) | Yes | Yes | No
/reciter/goldstandard/{uid} (GET) | Yes | Yes | No
/reciter/retrieve/articles/ | Yes | Yes | No
/reciter/retrieve/articles/by/uid | Yes | Yes | No
/reciter/sciencemetrix/smsid/{smsid} | Yes | Yes | No
/reciter/find/scopus/articles/pmids/ | Yes | Yes | No
/reciter/save/scopus/articles/ | Yes | Yes | No
/reciter/scopus/id | Yes | Yes | No
/reciter/scopusarticle/{pmid} | Yes | Yes | No
/pubmed/query-complex/ | Yes | Yes | No
/pubmed/query-doi/ | Yes | Yes | No
/pubmed/query-number-pubmed-articles/ | Yes | Yes | No
/pubmed/query/{query} | Yes | Yes | No

**Comment by paulalbert1** [comment]
@jl987-Jie - I spoke to Ounali and he said, "The problem with 3 is that it does exposes things to the public. 4 is fine with me. The only possible problem with 4 is the execution time limit.  If that's not a problem for you all, then great. From a security standpoint, 4 is probably preferable. "

**Comment by paulalbert1** [comment]
Sarbajit's to do list from Nov. 27, 2018 meeting:
- Generate SSO certificates for all our services
- Create DNS record in our DNS server and route53 in AWS
- Come up with DNS names for all our services (e.g., reciter.weill.cornell.edu) 
- implement roles for different APIs and certificates

**Comment by sarbajitdutta** [comment]
Added via PR #319
