### ISSUE TITLE
Delete unnecessary APIs and decomission/hide old codebases

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter#296]
In the interests of reducing confusion...

1. Why is the `Scopus-Controller` listed in the ReCiter Swagger UI if the `PubMed-Controller` is not? We should be consistent, right?

2. Should we get rid of these APIs as they look old? `/reciter/retrieve/articles/` and `/reciter/retrieve/articles/by/uid`?

3. Review the strategies in application.properties and remove any that are unused, e.g., board certification, citizenship, cocitation, article.size, etc.

 4. Delete/hide any repositories that have been subsumed by others. For example, ReCiter-Scopus-JPA, ReCiter-Scopus-Model. There are [7 PubMed repos](https://github.com/wcmc-its/?utf8=%E2%9C%93&q=pubmed&type=&language=) and [4 Scopus ones](https://github.com/wcmc-its/?utf8=%E2%9C%93&q=scopus&type=&language=).
@jl987-Jie - Could you please chime in on this?

**Comment by sarbajitdutta** [comment]
This has been taken care of.
