### ISSUE TITLE
Delete board certification, citizenship, dateInitialRun, dateLastRun, keywords, program, and pubMedAlias from identity data model

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter#318]
Also, check if we use pubMedAlias. I'm not sure we do.

Also, switch this to ENUM format....

<img width="1018" alt="screen shot 2019-01-21 at 4 12 33 pm" src="https://user-images.githubusercontent.com/3651640/51499250-80390b00-1d97-11e9-93a9-a192237d9b8b.png">

**Comment by sarbajitdutta** [comment]
This was done and a new version of Identity Model was pushed to maven central. Although pubmedAlias was kept due to current data in dynamodb.

Feel free to open this later @paulalbert1
