### ISSUE TITLE
Update Spring framework

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter#331]
https://github.com/wcmc-its/ReCiter/network/alert/pom.xml/org.springframework.security:spring-security-core/open

<img width="649" alt="Screen Shot 2019-04-16 at 5 15 15 PM" src="https://user-images.githubusercontent.com/3651640/56244595-3ea0bf00-606b-11e9-850d-a1726d523fb2.png">

**Comment by sarbajitdutta** [comment]
We are not using SeedFactory in our security feature. This will not affect us.

**Comment by paulalbert1** [comment]
<img width="980" alt="Screen Shot 2019-04-16 at 5 24 38 PM" src="https://user-images.githubusercontent.com/3651640/56245122-8e33ba80-606c-11e9-8dc2-5b4b1db8b966.png">
