### ISSUE TITLE
Allow ReCiter to be used as a web service by Academic Staff Management System

### ISSUE THREAD

**Issue by michaelbales1** [wcmc-its/ReCiter#37]
For every given CWID and PMID combination where a suggestion is positive or a user has provided feedback.

- Only output anything that ReCiter suggests.

## Outline

- Citation
  - pubDate
  - authorList
    - author1 (targetAuthor="N")
    - author2 (targetAuthor="Y")
    - author3 (targetAuthor="N")
    - ...
  - journal
    - verbose (full journal title)
    - medlineTA (title abbreviation)
  - volume
  - issue
  - pages
  - PMCID
  - DOI
- userAssertion (e.g., "accepted, rejected, null")
- Score
  - See below
- Evidence 
  - See below

## Score

An integer that can be used to sort suggestions in the web interface. 

+10 for email match
+2 for full exact name match (firstName, middle initial, lastName)
+1 for abbreviated name match (firstInitial, middle initial, lastName)
+1 for every other type of evidence... Count each instance of department, institutional affiliation, common collaborator, known relationship, etc. separately as an additional point.

## Evidence

This article was suggested for the following reasons:

### Name similarity

The name [John Smith] is similar or identical to an author of this article: {J. S. Smith}.

### Matching relationships

[John Smith] is associated with: {Curt Cole (as a co-investigator)}.

-OR, if two relationships-

[John Smith] is associated with: {Charles Smith (as a co-investigator)} and {Rainu Kaushal (as a mentor/mentee)}.

-OR, if three or more relationships--

[John Smith] is associated with: {Curtis Cole (as a co-investigator)}, {Rainu Kaushal (as a mentor/mentee)}, and {J. Schmitz (as a person in the same organizational unit)}.

### Affiliation match

The affiliation of the matching author in the article is {affiliation string}. This is consistent with the following:

- [jsmith@rocketmail.com] (known email)
- [Department of Genetic Medicine] (known departmental affiliation)
- [Emory University] (known institutional affiliation)
- [Hospital for Special Surgery] (a common-collaborator of [Weill Cornell Medicine])

### Grant match

[John Smith] is listed on grant #[grantNumber], which matches a grant number listed in the article record: {funding statement in article}.

### Timing of academic degrees

The article was published in {pubYear}, which is [#] years [before/after] [John Smith] received Bachelor's degree and [#] years [before/after] receiving a terminal degree.

### Clustering

The article was selected because it has the following in common with certain selected articles:

- This article shares MeSH major term of [MeSH major term] with <a class='data' href="https://www.ncbi.nlm.nih.gov/pubmed/?term=20000000+25000000%5Buid%5D">following article(s)</a>.
- This article cites <a class='data' href="https://www.ncbi.nlm.nih.gov/pubmed/?term=20000000+25000000%5Buid%5D">following article(s)</a>.
- This article is cited by <a class='data' href="https://www.ncbi.nlm.nih.gov/pubmed/?term=20000000+25000000%5Buid%5D">following article(s)</a>.
- A third <a class='data' href="https://www.ncbi.nlm.nih.gov/pubmed/?term=25000000%5Buid%5D">article</a> cites this article and a <a class='data' href="https://www.ncbi.nlm.nih.gov/pubmed/?term=25000000%5Buid%5D">clustered article</a>.
- This article is in the same journal, [Journal], as the clustered <a class='data' href="https://www.ncbi.nlm.nih.gov/pubmed/?term=25000000%5Buid%5D">article</a>.

**Comment by paulalbert1** [comment]
Duplicate issue. See #162
