### ISSUE TITLE
Add fields to the Article Retrieval and Feature Generator APIs

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter#425]
## Background 

To review, these are the APIs in order of when they're used.
1. Retrieve PubMed article from `/pubmed/query` API.
2. Optionally retrieve Scopus article metadata from `scopus/query` API.
3. Retrieve data from `/reciter/retrieve/articles/by/uid` API. If the Scopus integration exists, with this step, the system is combining data from PubMed and Scopus.
4. Output data via Feature Generator API `/reciter/feature-generator/by/uid`

In order to allow alternate approaches to clustering, we need to better expose the data used to make perform clustering. This will allow clustering to serve as an independent and allow us to more easily try different clustering strategies.

The following data below should be made available through both the Article Retrieval (`/pubmed/query`)  and Feature Generator APIs (`/reciter/feature-generator/by/uid`).

### How to determine
1. The `/pubmed/query` API outputs up to two ISSNs for a given article. Grab these identifiers.
2. Look up ISSN in `ScienceMetrix` table in DynamoDB, starting first with ISSN where issntype = `Linking`, then any others in any order. When you get a match, move on to next step.
3. Return `scienceMetrixSubfield` and `scienceMetrixSubfieldID`, mapping to fields to output `journalCategoryID` and `journalCategoryLabel`

### Sample data and output
For PMID = 31645720 and daa2028.
```
journalCategory
	journalCategoryID: 83,
	journalCategoryLabel: "General Science & Technology"
```

### Where to output
Child under `reCiterArticleFeatures`

### Prerequisite
1. Complete this issue: https://github.com/wcmc-its/ReCiter-PubMed-Retrieval-Tool/issues/28

### How to determine
1. The `/pubmed/query` API will output an array of identifiers that this article outputs. Grab the identifiers from the `ReferenceList` and the `CommentsCorrections` elements.
2. Combine them into a single array.

### Sample data and output
For PMID = 32025781 and tjfahey.
```
cites
  	articleIdentifiers: {"32020328","17563566", "27172433", "30672800"} , 
  	type: "pmid"
```

### Where to output
Child under `reCiterArticleFeatures`

### Prerequisite
1. Complete this issue: https://github.com/wcmc-its/ReCiter-PubMed-Retrieval-Tool/issues/28

### How to determine
1. The `/pubmed/query` API will output an array of identifiers that this article outputs. Grab the identifiers from _any other candidate articles_  from the `ReferenceList` and the `CommentsCorrections` elements which reference this article. (It is okay that we are not including some papers that don't reference this paper.
2. Combine them into a single array.

### Sample data and output
For PMID = 17115125 and rgcryst.
```
citedBy
  	articleIdentifiers: {"28273093"} , 
  	type: "pmid"
```

**Where to output** 
Child under `reCiterArticleFeatures`

### How to determine
1. The `/pubmed/query` API will output a series of values in `grantList.grantId`
2. Combine these values into a single array.

### Sample data and output
For PMID = 31645720 and daa2028.
```
grants
  	grantIdentifiers {"R01 AI074878", "R21 AI142213", "R01 AI095466"}
```

### Where to output
Child under `reCiterArticleFeatures`

### How to determine
1. The `/pubmed/query` API will output a series of keywords in `meshheadinglist`
2. Retrieve `descriptorname` where  `majortopicyn` = `Y` at least once.
3. Use MeSH term to look up `count` value in DynamoDB's `MeshTerm` table.

### Sample data and output
For PMID = 31645720 and daa2028.
```
"articleKeywords": [
    {
        "keyword": "Extinction, Psychological",
        "type": "MESH_MAJOR",
        "count": 7097
    },
    {
        "keyword": "Fear",
        "type": "MESH_MAJOR",
        "count": 52984
    },
    {
        "keyword": "Metabolomics",
        "type": "MESH_MAJOR",
        "count": 7768
    },
    {
        "keyword": "Microbiota",
        "type": "MESH_MAJOR",
        "count": 12143
    },
    {
        "keyword": "Neurons",
        "type": "MESH_MAJOR"
        "count": 551711
    }
],
```

### Where to output
Child under `reCiterArticleFeatures.articleKeywords`

### Background

The `/pubmed/query` API currently outputs the following.
```
{
  "lastname": "Alexopoulos",
  "forename": "George S",
  "initials": "GS",
  "affiliation": "Weill Cornell Institute of Geriatric Psychiatry, Weill Cornell Medicine, White Plains, NY, USA. gsalexop@med.cornell.edu.",
  "orcid": "http://orcid.org/0000-0001-5677-7001"
}
```

### How to determine
1. The `/pubmed/query` API will output affiliation statement and possible ORCID identifier for each author in `affiliation`. The `scopus/query` API will return affiliated institutional label and identifier for each author (can be multi-value).
2. Infer the presence of any email from PubMed affiliation statement. The email need not be matching. An example of this is johnsos and PMID = 20962132 where email = sbj2@columbia.edu.

### Sample data and output
For PMID = 32651477 and gsalexop.
```
"authorlist": [
  {
    "rank": 12,
    "lastname": "Alexopoulos",
    "forename": "George S",
    "initials": "GS",
    "targetAuthor": true,
    "affiliations": 
    	"affiliationStatementLabel": "Weill Cornell Institute of Geriatric Psychiatry, Weill Cornell Medicine, White Plains, NY, USA. gsalexop@med.cornell.edu.",
    	"affiliationStatementLabelSource": "PubMed",
    	"affiliationInstitutions": [
    		{
    			"affiliationInstitutionLabel": "Weill Cornell Institute of Geriatric Psychiatry", 
    			"affiliationInstitutionId": "60026978", 
    			"affiliationInstitutionSource": "Scopus"
    		}
    	],
    "email": "gsalexop@med.cornell.edu"
    "orcid": "http://orcid.org/0000-0001-5677-7001"
  },
```

### Where to output
Update existing features in `reCiterArticleFeatures.reCiterArticleAuthorFeatures`

**Comment by sarbajitdutta** [comment]
Done
