### ISSUE TITLE
PMID = 33316309 for personIdentifier = ram2045 has a high score and appears in ReCiterDB but doesn't appear in eSearchresults table or Feature Generator

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter#443]
These screenshots were all taken within 30 seconds of each other.

Also, featureGenerator
<img width="897" alt="Screen Shot 2020-12-18 at 7 18 46 AM" src="https://user-images.githubusercontent.com/3651640/102613889-4eef2400-4101-11eb-9fe7-f3134f61aaaf.png">
<img width="606" alt="Screen Shot 2020-12-18 at 7 14 57 AM" src="https://user-images.githubusercontent.com/3651640/102613687-f029aa80-4100-11eb-8a30-c0093b088c34.png">
<img width="1128" alt="Screen Shot 2020-12-18 at 7 14 03 AM" src="https://user-images.githubusercontent.com/3651640/102613694-f28c0480-4100-11eb-9545-015a8c84242b.png">
<img width="879" alt="Screen Shot 2020-12-18 at 7 16 55 AM" src="https://user-images.githubusercontent.com/3651640/102613725-06d00180-4101-11eb-8a61-f766ec919e47.png">

**Comment by sarbajitdutta** [comment]
@paulalbert1 I re-ran the Feature generator and it appears there. 

![image](https://user-images.githubusercontent.com/16959056/103008327-f35ad700-4502-11eb-9f1d-b9c0791c4907.png)

**Comment by paulalbert1** [comment]
@sarbajitdutta - I would assume as much. I was just trying to use this as a possible opportunity to address a bug. Oh well. Closing issue....
