### ISSUE TITLE
Update Feature Generator API so it returns count of pending publications for a scholar

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter#444]
Among all results output for Feature Generator, return the count of pending publications (where userAssertion = "NULL") for the chosen score threshold. If there's a count of zero, display that figure.

This value needs to be calculated dynamically in cases where no threshold is provided. So, for example, suppose user of Feature Generator does not provide a totalStandardizedArticleScore and application.properties is set with the following values....
```
totalArticleScore-standardized-default=7
reciter.minimumStorageThreshold=3 
```

Even though the database stores a record containing a value of countPendingArticles that reflects the number of articles of 3 or greater, the API should return the count of pending articles of 7 or greater.

In addition, the number of pending pubs should be exposed through group API.
/reciter/feature-generator/by/group

## Sample JSON

```
{
    "personIdentifier": "ram2045",
    "dateAdded": "2020-12-18T12:07:11.352+00:00",
    "dateUpdated": "2020-12-18T12:07:11.352+00:00",
    "mode": "AS_EVIDENCE",
    "overallAccuracy": 0.9984423676012462,
    "precision": 0.9968847352024922,
    "recall": 1.0,
    "countSuggestedArticles": 321,
    "countPendingArticles": 20,
    "reCiterArticleFeatures": [
        {
            "pmid": 30136449,
            "pmcid": "PMC6107364",
```

**Comment by sarbajitdutta** [comment]
@paulalbert1 This is done. Would need testing in dev. Once we push the article model changes to maven along with #442
