### ISSUE TITLE
Update Java 8 → 11

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter#446]
It seems ReCiter performs better with Java 11, especially when it comes to garbage collection. So we should require it with the next version.

## Test results 

meb7002
java8 feature generator, default flags
0.38 seconds

java8 feature generator, default flags + analysis refresh flag = true
3.16 seconds

java11 feature generator, default flags
0.39, 0.34, 0.19, 0.17, 0.18 seconds

java11 feature generator, default flags + analysis refresh flag = true
3.7 seconds

rak2007
java8 feature generator, default flags
0.64 seconds

java8 feature generator, default flags + analysis refresh flag = true
18.8 seconds

java11 feature generator, default flags
0.47, 0.22, 0.27 seconds

java11 feature generator, default flags + analysis refresh flag = true
14 seconds

**Comment by sarbajitdutta** [comment]
Updated the ReCiter java version to 11 and also updated the Dockerfile to reflect that. ReCiter would still work with Java 8.
