### ISSUE TITLE
Update Swagger from 2.0 → 3.0

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter#447]

**Comment by sarbajitdutta** [comment]
Upgrading from Swagger 2.0 to Swagger 3.0. The default swagger-ui url has changed from `http://<host>:<port>/swagger-ui.html` to `http://<host>:<port>/swagger-ui/index.html`. There is also a shortcut url now `http://<host>:<port>/swagger-ui/`. The trailing slash is required for the shortcut url to work.
