### ISSUE TITLE
Candidate article count is wrong

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter#454]
## ear2004
![image](https://user-images.githubusercontent.com/3651640/105756178-45d04e80-5f1a-11eb-83d2-52f2f24c1afc.png)

## pra9042
![image](https://user-images.githubusercontent.com/3651640/105756790-140bb780-5f1b-11eb-991e-e1eca7060482.png)

**Comment by sarbajitdutta** [comment]
@paulalbert1 is this happening for all users? Ideally the candidate article count would should include goldStandard count or just the cumulative  retrieval count for all strategies being used for that uid?

**Comment by paulalbert1** [comment]
@sarbajitdutta - It seems to be rather inconsistent. I found 2 examples. I checked a handful of others, and it seems to work just fine.

Desired behavior: cumulative retrieval count for all strategies being used for that uid.

**Comment by sarbajitdutta** [comment]
@paulalbert1  can you include the uid involved in the issue as well?

**Comment by paulalbert1** [comment]
@sarbajitdutta - Sure - so updated.

**Comment by paulalbert1** [comment]
@sarbajitdutta - This seems to be working pretty well, in general, but I did find a case where it was not. lig2002 supposedly has 10 candidate articles. PubMed [lists 630](https://pubmed.ncbi.nlm.nih.gov/?term=gerber+l%5Bau%5D&size=200).

Looking in esearchresults, the problems seems to be that the lookupType is set to ALL_PUBLICATIONS where retrievalStrategyName = EmailRetrievalStrategy.

In this case, shouldn't candidate article count refer to the count from FirstNameInitialRetrievalStrategy where lookupType = ALL_PUBLICATIONS? 

I know this doesn't exist, so maybe that's the problem??



```
{
  "esearchpmids": [
    {
      "lookupType": "ALL_PUBLICATIONS",
      "pmids": [
        21673530,
        19643003,
        23382401,
        26511854,
        16448897,
        28041591,
        22238239,
        12055419,
        33504256,
        17213753
      ],
      "retrievalDate": "2021-02-09T00:07:12.163Z",
      "retrievalStrategyName": "EmailRetrievalStrategy"
    },
```


<img width="1075" alt="Screen Shot 2021-02-25 at 5 10 33 PM" src="https://user-images.githubusercontent.com/3651640/109226323-90005600-778c-11eb-9a76-ee6271ae38ff.png">

**Comment by paulalbert1** [comment]
My use case is no longer a use case. Closing this issue for now.
