### ISSUE TITLE
Feature Generator by Group API should accept input of an array of person IDs

### ISSUE THREAD

**Issue by paulalbert1** [wcmc-its/ReCiter#482]
## Background

The existing Feature Generator by Group API `/reciter/feature-generator/by/group` currently returns a group of users according to these characteristics:
- departmentalAffiliation
- organizationalAffiliation
- personType

We need to allow curators the ability to return publications for an arbitrary, delimited list of person IDs independent of this list. 

This will be used in Publication Manager so curators can input a group of person IDs (CWIDs), and curate those users' publications / report on them.

## Requirement

We need three new fields:
- uids
- offset
- limit

### UIDs

Authorized users can use Feature Generator by Group API to input a list of person IDs (uids). The IDs would be delimited.

The most common delimiters we can expect users to enter are: space, line break, tab, and comma. We can enforce the use of a particular delimiter if you wish, but it would be nice, if not required, to accommodate all of these. Note that for the Publication Manager use case, this could also be handled on the application side.

When the uids field is populated, all other fields are ignored – except maxArticlesPerPerson and totalStandardizedArticleScore.

### Offset and limit

In addition, this API should be able to support OFFSET, LIMIT in the way that a SQL database does.

Offset is the count of the first record, and limit is the number of results returned.

**Comment by sarbajitdutta** [comment]
This is done - 3fb0e7ce8206590576e7fd2f7a4d588b296f5d8c

**Comment by sarbajitdutta** [comment]
Offset and limit is not required now and will revisit later.
