### ISSUE TITLE
Decrease likelihood of cluster assignment when co-author name is common

### ISSUE THREAD

**Issue by michaelbales1** [wcmc-its/ReCiter#96]
### Background

In phase one clustering, one clue that determines whether an article should be added to an existing cluster is the existence of a name that matches that of one of the existing author names for the cluster. This is one of the most important strategies used in ReCiter for agglomerative clustering. While the strategy is effective, merging errors can occur. Two factors that increase the statistical likelihood of a merging error are 1) higher numbers of co-authors on a paper, and 2) the frequency of authors with common names. The purpose of this enhancement is to measure whether authors have common names so that the likelihood of adding an article to a cluster may be decreased when the author has a common name.
### Operationalization
- For each author, use the Entrez e-utilities to determine how many articles would be returned for a query on the author's first name and middle initial. (Limit queries to one every 333 milliseconds to comply with Entrez requirements). Store the value.
- Use the result to decrease the likelihood that a candidate article is joined to the cluster based on co-author name match.

Alternative operationalization 1
- Identify the 500 most common author last names in Medline data. Assign each name a score based on its commonness.
- During phase one clustering, determine whether each co-author's last name is among the names in the list of most common names in Medline.
- If it is in the list, assign a score of 1 to the name.
- Use the result to decrease the likelihood that a candidate article is joined to the cluster based on co-author name match.

Alternative operationalization 2
- Download data for the past 1,000,000 records in Medline. Grab the author names and calculate their frequencies. Assign a frequency to names that occur 100 or more times. Use this as a lookup table to assess the extent to which any given name is common in Medline.
- Exploratory work is needed to determine whether it would be more useful to assign frequencies to complete names (e.g. Samuel Jones); to truncate first names (i.e. S. Jones); or to use last names (i.e. Jones).

**Comment by paulalbert1** [comment]
We're now doing this - sort of. During clustering, we will not consider 5 very common names.
